name: nwt_scroller
description: Quick Bible navigation overlay for JW Library
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window:
    path: plugins/flutter_overlay_window
  flutter_svg: ^2.2.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.0
  nwt_vibration:
    path: plugins/nwt_vibration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/bible.json
    - assets/svg/
